namespace Circus.OrderBook
{
    public enum OrderRejectedReason
    {
        MarketClosed,
        MarketPreOpen,
        InvalidQuantity,
        InvalidPriceIncrement,
        OrderNotInBook,
        OrderInBook,
        OrderIdAlreadyUsed,
        TooLateToCancel,
        NoOrdersToMatchMarketOrder,
        NoLastTradedPrice,
        TriggerPriceMustBeLessThanLastTradedPrice,
        TriggerPriceMustBeGreaterThanLastTradedPrice,
        TriggerPriceMustBeLessThanPrice,
        TriggerPriceMustBeGreaterThanPrice,
        NoChange,
        InvalidExpireDate,
        ClientOrderIdRequired,
        ClientOrderIdTooLong,
        CompanyIdRequired,
        CompanyIdTooLong,
        SelfMatchPreventionIdTooLong,
        PriceOutsideBands,
        MinQuantityOutOfRange,
        InsufficientLiquidityForMinQuantity,
        MaxVisibleQuantityOutOfRange
    }
}