<Project Sdk="Microsoft.NET.Sdk">

    <!-- TargetFramework, Nullable and IsPackable=false come from Directory.Build.props. -->

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Circus\Circus.csproj" />
      <ProjectReference Include="..\..\src\Circus.Simulator\Circus.Simulator.csproj" />
    </ItemGroup>

</Project>
