name: publish to nuget
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to request the OIDC token for trusted publishing
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Build
        run: dotnet build Circus/Circus.csproj -c Release

      - name: Pack
        run: dotnet pack Circus/Circus.csproj -c Release -o artifacts --no-build

      - name: NuGet login (OIDC -> temporary API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: seanoflynn

      - name: Push to NuGet
        run: dotnet nuget push "artifacts/*.nupkg" --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
